# Generated by Django 4.2 on 2024-08-14 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(blank=True, max_length=30, null=True)),
                ('item_catalogo', models.CharField(blank=True, max_length=30, null=True)),
                ('id_raiz', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogo_videojuegos_catalogos',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('apellidos_nombres', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('provincia', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'catalogo_videojuegos_clientes',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='catalogo_videojuegos.clientes')),
                ('id_forma_pago', models.ForeignKey(db_column='id_forma_pago', on_delete=django.db.models.deletion.CASCADE, related_name='forma_pago', to='catalogo_videojuegos.catalogos')),
            ],
            options={
                'db_table': 'catalogo_videojuegos_ventas',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('ano_lanzamiento', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('id_estado_producto', models.ForeignKey(db_column='id_estado_producto', on_delete=django.db.models.deletion.CASCADE, related_name='estado_producto', to='catalogo_videojuegos.catalogos')),
                ('id_formato', models.ForeignKey(db_column='id_formato', on_delete=django.db.models.deletion.CASCADE, related_name='formato', to='catalogo_videojuegos.catalogos')),
                ('id_genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='catalogo_videojuegos.catalogos')),
                ('id_plataforma', models.ForeignKey(db_column='id_plataforma', on_delete=django.db.models.deletion.CASCADE, related_name='plataforma', to='catalogo_videojuegos.catalogos')),
            ],
            options={
                'db_table': 'catalogo_videojuegos_inventario',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='catalogo_videojuegos.inventario')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='catalogo_videojuegos.ventas')),
            ],
            options={
                'db_table': 'catalogo_videojuegos_detalle_ventas',
            },
        ),
    ]
